/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'luisb' at '25/11/16 10:00' with Gradle 3.1
 *
 * @author luisb, @date 25/11/16 10:00
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
